apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc_netflix.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.svc_netflix.labels.app }}
  ports:
    - name: http-netflix
      protocol: TCP
      port: {{ .Values.svc_netflix.port }}        # Service Port
      targetPort: {{ .Values.svc_netflix.targetPort }}   # Container Port
  type: {{ .Values.svc_netflix.type }}