apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.deployment.labels.app}}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}        # Service Port
      targetPort: {{ .Values.service.targetPort }}   # Container Port
  type: {{ .Values.service.type }}